name: sec_analyzer
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pandas
  - requests
  - beautifulsoup4
  - lxml
  - pytest
  - pip:
    - streamlit>=1.28.0
    - python-dotenv>=0.19.0
    - PyPDF2>=3.0.0
    - python-docx>=0.8.11
    - ollama>=0.1.0
    - transformers>=4.21.0
    - torch>=2.0.0
    - black>=22.0.0
    - flake8>=5.0.0